---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:6.1.1
  armhf: ghcr.io/hassio-addons/debian-base/armhf:6.1.1
  i386: ghcr.io/hassio-addons/debian-base/i386:6.1.1
  armv7: ghcr.io/hassio-addons/debian-base/armv7:6.1.1
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:6.1.1
