---
name: Mycroft AI
version: 0.0.8
slug: mycroftai
description: Mycroft is an open source privacy-focused voice assistant. It can be installed on Linux, Raspberry Pi, our reference devices, or your own custom hardware.
url: https://github.com/PrimusNZ/hassio-addons/tree/master/mycroft
startup: application
arch:
  - amd64
  - aarch64
init: false
audio: true
host_network: true

image: ghcr.io/primusnz/hassio-addons/{arch}-mycroftai
