---
name: Mycroft AI
version: 0.0.6
slug: mycroft
description: A script to interrogate a Growatt Inverter for power information and publishes to MQTT. - Optionally uploads data to PVOutput
url: https://github.com/PrimusNZ/hassio-addons/tree/master/mycroft
startup: application
arch:
  - armhf
  - amd64
init: false
audio: true
host_network: true
image: ghcr.io/primusnz/mycroftai
