---
name: Growatt Interrogator
version: 0.0.4
slug: growatt_interrogator
description: A script to interrogate a Growatt Inverter for power information and publishes to MQTT. - Optionally uploads data to PVOutput
url: https://github.com/PrimusNZ/hassio-addons/
startup: application
arch:
  - armhf
  - amd64
hassio_api: true
init: false
options:
  inverter_port: /dev/ttyUSB0
  pvoutput_enabled: false

#devices:
#  - /dev/ttyUSB0

schema:
  inverter_port: str
  pvoutput_enabled: bool
  pvoutput_systemid: str?
  pvoutput_apikey: str?

uart: true
services:
  - mqtt:want
