---
name: Growatt Interrogator
version: 0.1.0
slug: growatt_interrogator
description: A script to interrogate a Growatt Inverter for power information and publishes to MQTT. - Optionally uploads data to PVOutput
url: https://github.com/PrimusNZ/hassio-addons/tree/master/growatt-interrogator
startup: application
arch:
  - armhf
  - amd64
hassio_api: true
init: false
options:
  inverter_port: /dev/ttyUSB0
  pvoutput_enabled: false
  verbose: false

schema:
  inverter_port: str
  pvoutput_enabled: bool
  pvoutput_systemid: str?
  pvoutput_apikey: str?
  verbose: bool

uart: true
services:
  - mqtt:want
image: ghcr.io/primusnz/growatt-interrogator