---
name: Mycroft AI
version: 0.0.1
slug: mycroft
description: A script to interrogate a Growatt Inverter for power information and publishes to MQTT. - Optionally uploads data to PVOutput
url: https://github.com/PrimusNZ/hassio-addons/tree/master/mycroft
startup: application
arch:
  - armhf
  - amd64
hassio_api: false
init: false
audio: true