name: Growatt Interrogator

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build
        uses: home-assistant/builder@master
        with:
          args: |
            --branch master \
            --all \
            --target growatt-interrogator \
            --docker-user ${{ github.repository_owner }} \
            --docker-password ${{ secrets.GITHUB_TOKEN }}
